USE [MainEcommerceDB]
GO
INSERT INTO [dbo].[Category]([Id], [Name], [ProductId])VALUES(1, 'Example Category', null)

GO
INSERT INTO [dbo].[Vendor]([Id], [vendor_name], [AddressId], [phone_number], [website], [email], [last_updatedtime], [note])VALUES(1, 'Habib Vendor', null, null, null, null, null, null)
INSERT INTO [dbo].[Vendor]([Id], [vendor_name], [AddressId], [phone_number], [website], [email], [last_updatedtime], [note])VALUES(2, 'Hyunbin Vendor', null, null, null, null, null, null)
INSERT INTO [dbo].[Vendor]([Id], [vendor_name], [AddressId], [phone_number], [website], [email], [last_updatedtime], [note])VALUES(3, 'Kevin Vendor', null, null, null, null, null, null)
INSERT INTO [dbo].[Vendor]([Id], [vendor_name], [AddressId], [phone_number], [website], [email], [last_updatedtime], [note])VALUES(4, 'Evan Vendor', null, null, null, null, null, null)
INSERT INTO [dbo].[Vendor]([Id], [vendor_name], [AddressId], [phone_number], [website], [email], [last_updatedtime], [note])VALUES(5, 'Julio Vendor', null, null, null, null, null, null)

GO
INSERT INTO [dbo].[Product]([Id], [Name], [DisplayName], [Description], [VendorId], [CategoryId], [ProductFormat], [QuantityPerUnit], [UnitPrice], [UnitsInStock], [Discount], [OrderAvailable], [ProductAvailable], [DiscountAvailable], [ImageId], [Note])VALUES(1,'Wifi Installation',				'Wifi Installation',					'Installing wifi at location',						1, null, 'Basic',			1,	100,		'True',		0.10, 1, 1, 1,	NULL,NULL)
INSERT INTO [dbo].[Product]([Id], [Name], [DisplayName], [Description], [VendorId], [CategoryId], [ProductFormat], [QuantityPerUnit], [UnitPrice], [UnitsInStock], [Discount], [OrderAvailable], [ProductAvailable], [DiscountAvailable], [ImageId], [Note])VALUES(2,'Wifi Installation',				'Wifi Installation',					'Installing wifi at location',						1, null, 'Normal',			1,	115,		'True',		null, 1, 1, 0,	NULL,NULL)
INSERT INTO [dbo].[Product]([Id], [Name], [DisplayName], [Description], [VendorId], [CategoryId], [ProductFormat], [QuantityPerUnit], [UnitPrice], [UnitsInStock], [Discount], [OrderAvailable], [ProductAvailable], [DiscountAvailable], [ImageId], [Note])VALUES(3,'Wifi Installation',				'Wifi Installation',					'Installing wifi at location',						1, null, 'Full',			1,	130,		'True',		null, 1, 1, 0,	NULL,NULL)
INSERT INTO [dbo].[Product]([Id], [Name], [DisplayName], [Description], [VendorId], [CategoryId], [ProductFormat], [QuantityPerUnit], [UnitPrice], [UnitsInStock], [Discount], [OrderAvailable], [ProductAvailable], [DiscountAvailable], [ImageId], [Note])VALUES(4,'Fiber optic cable Installation',	'Cable Installation',					'Installing Fiber Optic Cable',						1, null, 'Basic',			1,	120,		'True',		null, 1, 1, 0,	NULL,NULL)
INSERT INTO [dbo].[Product]([Id], [Name], [DisplayName], [Description], [VendorId], [CategoryId], [ProductFormat], [QuantityPerUnit], [UnitPrice], [UnitsInStock], [Discount], [OrderAvailable], [ProductAvailable], [DiscountAvailable], [ImageId], [Note])VALUES(5,'Fiber optic cable Installation',	'Cable Installation',					'Installing Fiber Optic Cable',						1, null, 'Normal',			1,	150,		'True',		0.15, 1, 1, 1,	NULL,NULL)
INSERT INTO [dbo].[Product]([Id], [Name], [DisplayName], [Description], [VendorId], [CategoryId], [ProductFormat], [QuantityPerUnit], [UnitPrice], [UnitsInStock], [Discount], [OrderAvailable], [ProductAvailable], [DiscountAvailable], [ImageId], [Note])VALUES(6,'Fiber optic cable Installation',	'Cable Installation',					'Installing Fiber Optic Cable',						1, null, 'Full',			1,	170,		'False',	null, 0, 0, 0,	NULL,NULL)
INSERT INTO [dbo].[Product]([Id], [Name], [DisplayName], [Description], [VendorId], [CategoryId], [ProductFormat], [QuantityPerUnit], [UnitPrice], [UnitsInStock], [Discount], [OrderAvailable], [ProductAvailable], [DiscountAvailable], [ImageId], [Note])VALUES(7,'Lord of the Ring - fellowship',	'Lord of the Ring - fellowship Book',	'LOTR soft copy',									2, null, 'Soft Copy',		2,	30,			'False',	null, 0, 0, 0,	NULL,NULL)
INSERT INTO [dbo].[Product]([Id], [Name], [DisplayName], [Description], [VendorId], [CategoryId], [ProductFormat], [QuantityPerUnit], [UnitPrice], [UnitsInStock], [Discount], [OrderAvailable], [ProductAvailable], [DiscountAvailable], [ImageId], [Note])VALUES(8,'To Kill A Mocking Bird', 			'To Kill A Mocking Bird book',			'TKAMB hard copy',									2, null, 'Hard Copy',		4,	40.99,		'True',		0.30, 1, 1, 1,	NULL,NULL)
INSERT INTO [dbo].[Product]([Id], [Name], [DisplayName], [Description], [VendorId], [CategoryId], [ProductFormat], [QuantityPerUnit], [UnitPrice], [UnitsInStock], [Discount], [OrderAvailable], [ProductAvailable], [DiscountAvailable], [ImageId], [Note])VALUES(9,'Coke - Pack#1',					'6 Pack of Coca Cola',					'Pack of Coca Cola',								3, null, 'Warehouse Item',	1,	7.50,		'True',		null, 1, 1, 0,	NULL,NULL)
INSERT INTO [dbo].[Product]([Id], [Name], [DisplayName], [Description], [VendorId], [CategoryId], [ProductFormat], [QuantityPerUnit], [UnitPrice], [UnitsInStock], [Discount], [OrderAvailable], [ProductAvailable], [DiscountAvailable], [ImageId], [Note])VALUES(10,'Ginger Ale',						'6 Pack of Ginger Ale',					'Pack of Ginger Ale',								3, null, 'Warehouse Item',	1,	6.50,		'True',		null, 1, 1, 0,	NULL,NULL)																																				    
INSERT INTO [dbo].[Product]([Id], [Name], [DisplayName], [Description], [VendorId], [CategoryId], [ProductFormat], [QuantityPerUnit], [UnitPrice], [UnitsInStock], [Discount], [OrderAvailable], [ProductAvailable], [DiscountAvailable], [ImageId], [Note])VALUES(11,'Necklace',						'Cross Necklace',						'Sterling Silver Thin 0.6mm Box Chain Necklace',	4, null, 'Warehouse Item',	3,	19,			'False',	null, 0, 0, 0,	NULL,NULL)
INSERT INTO [dbo].[Product]([Id], [Name], [DisplayName], [Description], [VendorId], [CategoryId], [ProductFormat], [QuantityPerUnit], [UnitPrice], [UnitsInStock], [Discount], [OrderAvailable], [ProductAvailable], [DiscountAvailable], [ImageId], [Note])VALUES(12,'Hot Wheels Car',					'Fast and Furios Paul Walker Car',		'Hot wheels R/C 1:64 Mini Nissan Skyline',			5, null, 'Warehouse Item',	5,	13,			'True',		null, 1, 1, 0,	NULL,NULL)		




