USE [MainEcommerceDB]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

DROP TABLE IF EXISTS [dbo].[PaymentMethod];

CREATE TABLE [dbo].[PaymentMethod](
	[Id] [nvarchar](255) NOT NULL,
	[Description] [nvarchar](255) NOT NULL,
	[TrnCode] [nvarchar](255) NOT NULL,
	[MethodCode] [varchar](2) NOT NULL,

 CONSTRAINT [PK_Payment] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO